config/routes.rb
Rails.application.routes.draw do
  resources :class_session_students
  resources :class_sessions
  resources :trainings
  resources :students
  resources :instructors
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/training.rb
class Training < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "durantion_minutes", "id", "id_value", "name", "reps", "single", "updated_at"]
    end

    include Pagy::Frontend
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  include Pagy::Backend

  before_action :set_training, only: %i[ show edit update destroy ]

  # GET /trainings or /trainings.json
  def index
    #@trainings = Training.all
    @q = Training.ransack(params[:q])
    @pagy, @trainings = pagy(@q.result, items: 10)
  end

  # GET /trainings/1 or /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings or /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to training_url(@training), notice: "Treino incluido com sucesso!" }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1 or /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to training_url(@training), notice: "Treino atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1 or /trainings/1.json
  def destroy
    

    begin
      @training.destroy!
      respond_to do |format|
        format.html { redirect_to trainings_url, notice: "Treino deletado com sucesso!" }
        format.json { head :no_content }
      end
    rescue
      respond_to do |format|
        format.html { redirect_to trainings_url, alert: "Treino não pode ser deletado pois está vínculado a outra tela!" }
        format.json { head :no_content }
      end
    end    
  end

  def clear_filters
    # Você pode redefinir os parâmetros de pesquisa para seus valores padrão aqui
    p "caiu no clear_filters"
    redirect_to training_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit(:name, :single, :reps, :durantion_minutes)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
    include Pagy::Frontend
end

app/views/trainings/_form.html.erb
<%= form_with(model: training) do |form| %>
  <% if training.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(training.errors.count, "error" ) %> prohibited this training from being saved:
      </h2>

      <ul>
        <% training.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="form-group row">
        <div class="col-md-4">
          <%= form.label :name,"Nome", style: "display: block" , class: "col-md-6 col-form-label text-md-right" %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-4">
          <%= form.label :single,"Treino Sozinho?", style: "display: block" ,
            class: "col-md-6 col-form-label text-md-right" %>
            <%= form.check_box :single %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :durantion_minutes,"Duração (minutos)", style: "display: block" ,
            class: "col-md-6 col-form-label text-md-right" %>
            <%= form.number_field :durantion_minutes, class: "form-control" %>
        </div>
      </div>
      </br>
      <div>
        <%= form.submit "Salvar" , class: "btn btn-primary" %>
      </div>

      <% end %>

app/views/trainings/_training.html.erb
<div id="<%= dom_id training %>">
  <p>
    <strong>Nome:</strong>
    <%= training.name %>
  </p>

  <p>
    <strong>Treino sozinho?:</strong>
    <%= training.single ? "Sim" : "Não" %>
  </p>

  <p>
    <strong>Duração (minutos):</strong>
    <%= training.durantion_minutes %>
  </p>

</div>

app/views/trainings/edit.html.erb
<h1>Editar Treino</h1>

<%= render "form", training: @training %>

<br>

<div>
  <%= link_to "Detalhes", @training %> |
  <%= link_to "Voltar", trainings_path %>
</div>

app/views/trainings/index.html.erb
<h1>Treinos</h1>

<div class="accordion" id="accordionExample">

  <div class="accordion-item">
  
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Filtros
      </button>
    </h2>
  
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
     
        <div class="card-body">
          <%= search_form_for @q, remote: true do |f| %>
            <table>

                <tr>

                  <td>
                    <div class="filter-field">
                      <%= f.label :name_cont, 'Nome' , class: "col-md-6 col-form-label text-md-right" %>
                      <%= f.search_field :name_cont, class: "form-control" %>
                    </div>
                  </td>
             
                </tr>

              <tr>
                <td colspan="2">
                  <%= f.submit 'Filtrar' , class: 'btn btn-primary' %>
                    <%= link_to 'Limpar Filtros' , trainings_path, method: :get, class: 'btn btn-secondary' ,
                      style: 'margin-left: 10px;' %>
                </td>
              </tr>
        
            </table>
            <% end %>
        </div>

      </div>
    </div>
  
  </div>

</div>

</br>

<%= link_to "Novo", new_training_path, class: 'btn btn-success' %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Individual?</th>
      <th scope="col">Duração (minutos)</th>
      <th scope="col">Editar</th>
      <th scope="col">Remover</th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
    <tr>
      <td><%= training.name %></td>
      <td><%= training.single %></td>
      <td><%= training.durantion_minutes %></td>
      <td><%= button_to 'Editar', edit_training_path(training), method: 'get', class: 'btn btn-primary' %></td>
      <td><%= button_to 'Remover', training_path(training), method: 'delete', data: {turbo_confirm: "Deseja mesmo deletar esse registro?"} , class: 'btn btn-danger ' %></td>
    </tr>
    <% end %>
  </tbody>


</table>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/trainings/new.html.erb
<h1>Novo Treino</h1>

<%= render "form", training: @training %>

<br>

<div>
  <%= link_to "Voltar", trainings_path %>
</div>

app/views/trainings/show.html.erb
<%= render @training %>

<div>
  <%= link_to "Editar", edit_training_path(@training) %> |
  <%= link_to "Voltar", trainings_path %>

  <%= button_to "Deletar", @training, method: :delete, class: "btn btn-danger" %>
</div>