config/routes.rb
Rails.application.routes.draw do
  resources :class_session_students
  resources :class_sessions
  resources :trainings
  resources :students
  resources :instructors
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  
  def self.ransackable_attributes(auth_object = nil)
    ["birth", "created_at", "document", "email", "id", "id_value", "name", "phone", "specialities", "updated_at", "user_id"]
  end

  belongs_to :user
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  include Pagy::Backend
  before_action :set_instructor, only: %i[ show edit update destroy ]

  # GET /instructors or /instructors.json
  def index
    @q = Instructor.ransack(params[:q])
    @pagy, @instructors = pagy(@q.result, items: 10)
  end

  # GET /instructors/1 or /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors or /instructors.json
  def create
   
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      @instructor.user_id = current_user.id
      if @instructor.save
        format.html { redirect_to instructor_url(@instructor), notice: "Instrutor incluido com sucesso!" }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1 or /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to instructor_url(@instructor), notice: "Instrutor atrualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1 or /instructors/1.json
  def destroy
    begin
      @instructor.destroy!
      respond_to do |format|
        format.html { redirect_to instructors_url, notice: "Instrutor deletado com sucesso!" }
        format.json { head :no_content }
      end
    rescue ActiveRecord::InvalidForeignKey
      respond_to do |format|
        format.html { redirect_to instructors_url, alert: "Instrutor não pode ser deletado pois está vinculado a outra tela!" }
        format.json { head :no_content }
      end
    end
  end

  def clear_filters
    # Você pode redefinir os parâmetros de pesquisa para seus valores padrão aqui
    p "caiu no clear_filters"
    redirect_to instructor_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
      p "*********** current_user.id",current_user.id
      @instructor.user_id = current_user.id
    end

    # Only allow a list of trusted parameters through.
    def instructor_params
      params.require(:instructor).permit(:name, :birth, :email, :document, :phone, :specialities, :user_id)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
    include Pagy::Frontend
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor) do |form| %>
  <% if instructor.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(instructor.errors.count, "error" ) %> prohibited this instructor from being saved:
      </h2>

      <ul>
        <% instructor.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="form-group row">
        <div class="col-md-4">
          <%= form.label :name, "Nome:" , style: "display: block" , class: "col-md-6 col-form-label text-md-right" %>
            <%= form.text_field :name , class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :birth, "Data de Nascimento" , class: "col-md-6 col-form-label text-md-right" %>
            <%= form.date_field :birth, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :email, "Email" , style: "display: block" , class: "col-md-6 col-form-label text-md-right" %>
            <%= form.text_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :document, "Documento" , style: "display: block",class: "col-md-6 col-form-label text-md-right" %>
            <%= form.text_field :document, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <%= form.label :phone, "Celular", style: "display: block", class: "col-md-6 col-form-label text-md-right" %>
            <%= form.text_field :phone, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-mod-2">
          <%= form.label :specialities, "Especialidades", style: "display: block", class: "" %>
            <%= form.text_area :specialities, class: "form-control small-textarea", cols: 30 %>
        </div>
      </div>

      <!-- <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div> -->
</br>
      <div>
        <%= form.submit "Salvar", class: "btn btn-primary"  %>
      </div>
<% end %>

app/views/instructors/_instructor.html.erb
<div id="<%= dom_id instructor %>">
  <p>
    <strong>Name:</strong>
    <%= instructor.name %>
  </p>

  <p>
    <strong>Birth:</strong>
    <%= instructor.birth %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= instructor.email %>
  </p>

  <p>
    <strong>Document:</strong>
    <%= instructor.document %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= instructor.phone %>
  </p>

  <p>
    <strong>Specialities:</strong>
    <%= instructor.specialities %>
  </p>

  <p>
    <strong>User:</strong>
    <%= instructor.user_id   %>
  </p>

</div>

app/views/instructors/edit.html.erb
<h1>Editar Instrutor</h1>

<%= render "form", instructor: @instructor %>

<br>

<div>
  <%= link_to "Detalhes", @instructor %> |
  <%= link_to "Voltar", instructors_path %>
</div>

app/views/instructors/index.html.erb
<h1>Instrutores</h1>

<div class="accordion" id="accordionExample">

  <div class="accordion-item">
  
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Filtros
      </button>
    </h2>
  
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
     
        <div class="card-body">
          <%= search_form_for @q, remote: true do |f| %>
            <table>

                <tr>

                  <td>
                    <div class="filter-field">
                      <%= f.label :name_cont, 'Nome' , class: "col-md-6 col-form-label text-md-right" %>
                      <%= f.search_field :name_cont, class: "form-control" %>
                    </div>
                  </td>

                  <td>  
                    <div class="filter-field">
                      <%= f.label :document_cont, 'Documento'  , class: "col-md-6 col-form-label text-md-right" %>
                      <%= f.search_field :document_cont , class: "form-control" %>
                    </div>
                  </td>
                  
                  <td>
                    <div class="filter-field">
                      <%= f.label :email_cont, 'Email'  , class: "col-md-6 col-form-label text-md-right" %>
                      <%= f.search_field :email_cont , class: "form-control" %>
                    </div>
                  </td>
             
                </tr>

              <tr>
                <td colspan="2">
                  <%= f.submit 'Filtrar' , class: 'btn btn-primary' %>
                    <%= link_to 'Limpar Filtros' , instructors_path, method: :get, class: 'btn btn-secondary' ,
                      style: 'margin-left: 10px;' %>
                </td>
              </tr>
        
            </table>
            <% end %>
        </div>

      </div>
    </div>
  
  </div>

</div>

</br>

<%= link_to "Novo", new_instructor_path, class: 'btn btn-success' %>

<div id="instructors">
  <table class="table"> 
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Documento</th>
        <th scope="col">Editar</th>
        <th scope="col">Excluir</th>
      </tr>
    </thead>
  
    <tbody>
     <% @instructors.each do |instructor| %>
          <tr>
            <td><%= instructor.name %></td>
            <td><%= instructor.email %></td>
            <td><%= instructor.document %></td>
            <td><%= button_to 'Editar', edit_instructor_path(instructor), method: 'get', class: 'btn btn-primary'%></td>
            <td><%= button_to 'Remover',  instructor_path(instructor), method: 'delete', data: { turbo_confirm: "Deseja mesmo deletar esse registro?" }, class: 'btn btn-danger'%></td>  
          </tr>
      <% end %>
  
    </tbody>
  
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/instructors/new.html.erb
<h1>Novo Instrutor</h1>

<%= render "form", instructor: @instructor %>

<br>

<div>
  <%= link_to "Voltar", instructors_path %>
</div>

app/views/instructors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @instructor %>

<div>
  <%= link_to "Editar Instrutor", edit_instructor_path(@instructor) %> |
  <%= link_to "Voltar", instructors_path %>

  <%= button_to "Deletar", @instructor, method: :delete, class: "btn btn-danger" %>
</div>