config/routes.rb
Rails.application.routes.draw do
  resources :class_session_students
  resources :class_sessions
  resources :trainings
  resources :students
  resources :instructors
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/class_session.rb
class ClassSession < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["active", "created_at", "description", "end_time", "id", "id_value", "instructor_id", "name", "start_time", "training_id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["class_session_students", "instructor", "students", "training"]
  end

  belongs_to :instructor
  belongs_to :training

  #has_many :class_session_students, dependent: :destroy
  has_many :class_session_students
  has_many :students, through: :class_session_students
  
end

app/controllers/class_sessions_controller.rb
class ClassSessionsController < ApplicationController
  
  include Pagy::Backend

  before_action :set_class_session, only: %i[ show edit update destroy ]

  # GET /class_sessions or /class_sessions.json
  def index
   @q = ClassSession.ransack(params[:q])
   @pagy, @class_sessions = pagy(@q.result, items: 10)
  end

  # GET /class_sessions/1 or /class_sessions/1.json
  def show
  end

  # GET /class_sessions/new
  def new
    @class_session = ClassSession.new
  end

  # GET /class_sessions/1/edit
  def edit
  end

  # POST /class_sessions or /class_sessions.json
  def create
    @class_session = ClassSession.new(class_session_params)

    respond_to do |format|
      if @class_session.save
        format.html { redirect_to class_session_url(@class_session), notice: "Turma incluida com sucesso!" }
        format.json { render :show, status: :created, location: @class_session }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @class_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_sessions/1 or /class_sessions/1.json
  def update
    respond_to do |format|
      if @class_session.update(class_session_params)
        format.html { redirect_to class_session_url(@class_session), notice: "Turma atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @class_session }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @class_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_sessions/1 or /class_sessions/1.json
  def destroy
    begin
    @class_session.destroy!

    respond_to do |format|
      format.html { redirect_to class_sessions_url, notice: "Turma deletada com sucesso!" }
      format.json { head :no_content }
    end
  rescue ActiveRecord::InvalidForeignKey
    respond_to do |format|
      format.html { redirect_to class_sessions_url, alert: "Turma não pode ser deletada poís está vínculada a outra tela!" }
      format.json { head :no_content }
      end
    end  
  end

  def clear_filters
    # Você pode redefinir os parâmetros de pesquisa para seus valores padrão aqui
    p "caiu no clear_filters"
    redirect_to class_sessions_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_session
      @class_session = ClassSession.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def class_session_params
      params.require(:class_session).permit(:name, :description, :active, :start_time, :end_time, :instructor_id, :training_id)
    end
end

app/helpers/class_sessions_helper.rb
module ClassSessionsHelper
    include Pagy::Frontend
end

app/views/class_sessions/_class_session.html.erb
<div id="<%= dom_id class_session %>">
  <p>
    <strong>Name:</strong>
    <%= class_session.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= class_session.description %>
  </p>

  <p>
    <strong>Ativa:</strong>
    <%= class_session.active %>
  </p>

  <p>
    <strong>Hora inicio:</strong>
    <%= class_session.start_time %>
  </p>

  <p>
    <strong>Hora fim:</strong>
    <%= class_session.end_time %>
  </p>

  <p>
    <strong>Instrutor:</strong>
    <%= class_session.instructor_id %>
  </p>

  <p>
    <strong>Treino:</strong>
    <%= class_session.training_id %>
  </p>

</div>

app/views/class_sessions/_form.html.erb
<%= form_with(model: class_session) do |form| %>
  <% if class_session.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(class_session.errors.count, "error") %> prohibited this class_session from being saved:</h2>

      <ul>
        <% class_session.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-md-4">
      <%= form.label :name, "Nome", style: "display: block", class: "col-md-6 col-form-label text-md-right" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-4">
      <%= form.label :description, "Descrição", style: "display: block", class: "col-md-6 col-form-label text-md-right" %>
      <%= form.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-4">
      <%= form.label :active, "Ativa", style: "display: block", class: "col-md-6 col-form-label text-md-right" %>
      <%= form.check_box :active %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :start_time, "Hora Inicio", style: "display: block", class: "col-md-6 col-form-label text-md-right" %>
      <%= form.datetime_field :start_time , class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :end_time, "Hora Fim", style: "display: block", class: "col-md-6 col-form-label text-md-right" %>
      <%= form.datetime_field :end_time , class: "form-control" %>
    </div>
  </div>


  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :instructor_id, "Instrutor", style: "display: block" %>
      <% instructor_array = Instructor.all.map { |instructor| [instructor.name, instructor.id] } %>
      <%= form.select :instructor_id, options_for_select(instructor_array), {}, class: "form-control"  %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :training_id, "Treino", style: "display: block", class: "col-md-6 col-form-label text-md-right" %>
      <% training_array = Training.all.map { |training| [training.name, training.id] } %>
      <%= form.select :training_id, options_for_select(training_array), {}, class: "form-control" %>
    </div>
  </div>

  </br>

  <div>
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/class_sessions/edit.html.erb
<h1>Editar turma</h1>

<%= link_to "Ver alunos da turma", class_session_students_path(class_session_id: @class_session.id), class: 'btn btn-primary' %>

<%= render "form", class_session: @class_session %>

<br>

<div>
  <%= link_to "Voltar", class_sessions_path %>
</div>

app/views/class_sessions/index.html.erb
<h1>Turma</h1>

<div class="accordion" id="accordionExample">

  <div class="accordion-item">
  
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Filtros
      </button>
    </h2>
  
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
     
        <div class="card-body">
          <%= search_form_for @q, remote: true do |f| %>
            <table>

                <tr>

                  <td>
                    <div class="filter-field">
                      <%= f.label :name_cont, 'Nome' , class: "col-md-6 col-form-label text-md-right" %>
                      <%= f.search_field :name_cont, class: "form-control" %>
                    </div>
                  </td>

                  <td>
                    <div class="filter-field">
                      <%= f.label :description_cont, 'Descrição' , class: "col-md-6 col-form-label text-md-right" %>
                      <%= f.search_field :description_cont, class: "form-control" %>
                    </div>
                  </td>

                  <td>
                    <div class="filter-field">
                      <%= f.label :instructor_id, "Instrutor", style: "display: block" %>
                      <% instructor_array = Instructor.all.map { |instructor| [instructor.name, instructor.id] } %>
                      <%= f.select :instructor_id_eq, options_for_select(instructor_array), { include_blank: 'Selecione o Instrutor' }, class: "form-control" %>
                    </div>
                  </td>
                 
                  <td>
                    <div class="filter-field">
                      <%= f.label :training_id, "Treino", style: "display: block" %>
                      <% training_array = Training.all.map { |training| [training.name, training.id] } %>
                      <%= f.select :training_id_eq, options_for_select(training_array), { include_blank: 'Selecione o Treino' }, class: "form-control" %>
                    </div>
                  </td>
       
                </tr>

              <tr>
                <td colspan="2">
                  <%= f.submit 'Filtrar' , class: 'btn btn-primary' %>
                    <%= link_to 'Limpar Filtros' , class_sessions_path, method: :get, class: 'btn btn-secondary' ,
                      style: 'margin-left: 10px;' %>
                </td>
              </tr>
        
            </table>
            <% end %>
        </div>

      </div>
    </div>
  
  </div>

</div>

<%= link_to "Novo", new_class_session_path, class: 'btn btn-success' %>

<div id="turmas">
  
  <table class="table">
    <thead>
        <tr>
          <th>Nome</th>
          <th>Descrição</th>
          <th>Ativa?</th>
          <th>Hora Inicio</th>
          <th>Hora Fim</th>
          <th>Instrutor</th>
          <th>Treino</th>
          <th scope="col">Editar</th>
          <th scope="col">Excluir</th>
        </tr>
    </thead>
    
    <tbody>
      <% @class_sessions.each do |turma| %>
        <tr>
          <td><%= turma.name %></td>
          <td><%= turma.description %></td>
          <td><%= turma.active %></td>
          <td><%= turma.start_time %></td>
          <td><%= turma.end_time %></td>
          <td><%= turma.instructor.name %></td>
          <td><%= turma.training.name %></td>
          <td><%= button_to 'Editar', edit_class_session_path(turma), method: 'get', class: 'btn btn-primary' %></td>
          <td><%= button_to 'Remover',  class_session_path(turma), method: 'delete', data: { turbo_confirm: "Deseja mesmo deletar esse registro?" }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/class_sessions/new.html.erb
<h1>Nova Turma</h1>

<%= render "form", class_session: @class_session %>

<br>

<div>
  <%= link_to "Back to class sessions", class_sessions_path %>
</div>

app/views/class_sessions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @class_session %>

<div>
  <%= link_to "Edit this class session", edit_class_session_path(@class_session) %> |
  <%= link_to "Back to class sessions", class_sessions_path %>

  <%= button_to "Destroy this class session", @class_session, method: :delete %>
</div>