config/routes.rb
Rails.application.routes.draw do
  resources :class_session_students
  resources :class_sessions
  resources :trainings
  resources :students
  resources :instructors
  devise_for :users
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_footer.html.erb
<footer>
    <p><%= Time.zone.now.year %> LaunchGym</p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #98caff;">
    <div class="container-fluid">
        <%= link_to "LaunchGym", :root, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <% if user_signed_in? %>    
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"> <%= link_to "Turma", class_sessions_path, class: "nav-link"  %></li>
                    <li class="nav-item"> <%= link_to "Treino", trainings_path, class: "nav-link"  %></li>
                    <li class="nav-item"> <%= link_to "Aluno", students_path, class: "nav-link"  %></li>
                    <li class="nav-item"> <%= link_to "Instrutor", instructors_path, class: "nav-link"  %></li>
                </ul>
            <% end %>
            <ul class="navbar-nav">
                <% if user_signed_in? %>      
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li class="nav-item"> <%= link_to "Editar conta", edit_user_registration_path, class: "nav-link"  %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li class="nav-item"> <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-small btn-danger mx-2" %></li>
                        </ul>
                    </li>
                <% else %>
                    <li class="nav-item"> <%= link_to "Inscrever-se", new_user_registration_path, class: "nav-link"  %></li>
                    <li class="nav-item"> <%= link_to "Entrar", new_user_session_path, class: "nav-link"  %></li>
                <% end %>
            </ul>      
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Launchgym</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    </br>

    <div class="container-fluid">
      <% if false %> 
        <p> Usuário logado: <%=  user_signed_in? %>  </p> 
      <% end %> 
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>